const   PROGRAMS = [
    {
        id: "ghtxbeyrjnzv8ar",
        title: "demining Cambodia",
        where: "At the provinces in cambodia",
        info: "According to the CMAC, there are around 4 to 6 million landmines in Cambodia, while some are estimating even 10 million. This is a large amount of mines, which poses a threat to public safety. People shouldn't walk every day and be scared that they one day might step on a landmine and die. So we at the Valsella Foundation are offering you to volunteer to help demine Cambodia. We will ensure your safety while demining the landmines with professionals that will help guide you.",
        video: "https://www.youtube.com/embed/qbmyK6GYMQ8?si=lW8mYZNGnWYcDczZ",
        username: "Vince Masuka",
        image: "./images/2232.jpg",
        testimony: "Volunteering with the Valsella Foundation on their demining program in Cambodia has been a life-changing experience for me. When I first signed up, I knew I was stepping into a project that was vital for the safety and well-being of countless people, but I didn't realize how profoundly it would impact my own life. Cambodia, with its rich history and beautiful landscapes, unfortunately bears the heavy legacy of landmines from past conflicts. These hidden dangers have long threatened the lives and livelihoods of its people. Being part of a team committed to removing these deadly remnants has been incredibly rewarding. Every landmine we safely dispose of not only saves lives but also helps to reclaim land for safe use, allowing communities to thrive once more. The training provided by Valsella Foundation was thorough and empowering. We learned how to use advanced demining equipment and followed strict safety protocols. The professionalism and dedication of the team were evident in every aspect of our work. We collaborated with local experts and international advisors, ensuring that our efforts were effective and culturally sensitive. One of the most memorable aspects of this volunteer program has been the interactions with the local communities. Seeing the relief and gratitude on the faces of families who can now safely return to their homes is indescribable. We’ve seen children walking to school on cleared paths, farmers working their fields without fear, and villages beginning to rebuild and prosper. These moments of joy and hope are a testament to the profound impact of our efforts. Volunteering in Cambodia has taught me the true meaning of resilience and community spirit. The Cambodian people’s strength and determination have been a constant source of inspiration. This experience has not only made me more aware of global issues but has also instilled in me a deeper sense of responsibility and compassion. I would highly recommend Valsella Foundation’s demining volunteer program to anyone looking to make a tangible difference in the world. It’s a challenging but immensely rewarding experience that shows you the power of collective action and the importance of giving back. The skills I’ve gained and the memories I’ve made will stay with me forever, reminding me of the incredible impact we can have when we come together for a common cause."
    },
    {
        id: "n4ag2ssujax3nv2",
        title: "Assisting Disabled people",
        where: "Phnom Penh",
        info: "According to Khmer times, there are around 300,000 disabled people in Cambodia. There are a lot of people that do not live comfortably because of the poor healthcare system in Cambodia. so we will assist these people so they can live their lives comfortably.",
        video: "https://www.youtube.com/embed/SStrXEFU8dk?si=X-KojSeoJeBQuXdO",
        username: "Dexter Wolfe",
        image: "./images/Michael_C._Hall_as_Dexter_Morgan_publicity_photo,_2012.webp",
        testimony: "Volunteering with the Valsella Foundation's program to assist disabled people in Cambodia has been one of the most enriching and humbling experiences of my life. From the moment I arrived, I was struck by the warmth and resilience of the Cambodian people. The work we did together was not just about providing support, but about fostering inclusion and dignity. The program's focus on providing mobility aids, vocational training, and healthcare services meant that we were able to make a real difference in the lives of many individuals. One of the most memorable moments for me was helping to set up a wheelchair for a young girl named Srey. Her joy and newfound independence were incredibly moving. It was a powerful reminder of how much we can achieve when we work together to break down barriers. We also conducted workshops to promote awareness and understanding of disability issues within the local community. It was inspiring to see the positive changes in attitudes and the increased willingness to support people with disabilities. The sense of community and solidarity that developed was truly heartwarming. Throughout my time with the program, I was continually amazed by the strength and determination of the individuals we worked with. Their stories of overcoming adversity and striving for a better future were a source of constant inspiration. The skills and confidence they gained through our efforts opened up new opportunities for them, allowing them to participate more fully in all aspects of life. This experience has not only broadened my understanding of the challenges faced by disabled individuals but has also deepened my commitment to advocacy and inclusion. I am incredibly grateful for the opportunity to be part of such a meaningful and impactful program. The connections I made and the lessons I learned will stay with me forever, reminding me of the importance of compassion and community."
    },
    {
        id: "y1j0cnvo3a3mwdx",
        title: "Helping in Orphanages",
        where: "Phnom Penh",
        info: "There are around half a million orphans living in Cambodia right now. They are innocent children that need guidance from people to actually have a great future and have great morals. That's why we need you to help these children. We can gather water, food, and clothes for these children while also teaching them to be smart and great as adults.",
        video: "https://www.youtube.com/embed/5EN3_7Nl0Qk?si=_hWZjZN-2Jz--D9r",
        username: "Walter Blake",
        image: "./images/download.webp",
        testimony: "Volunteering with Valsella Foundation in Cambodian orphanages has been one of the most heartwarming and transformative experiences of my life. From the very first day, I felt a profound connection with the children and the community, and the impact of our work became immediately apparent. The children in these orphanages have faced incredible challenges, yet their resilience and optimism are truly inspiring. As a volunteer, my role was to support their education, provide emotional comfort, and create a nurturing environment where they could thrive. Whether it was through organizing educational activities, assisting with homework, or simply playing games, every moment spent with these children was filled with joy and purpose. One of the most unforgettable moments was when we organized a cultural exchange event. The excitement and enthusiasm of the children were contagious as they showcased their talents in dance, music, and art. It was a powerful reminder of the boundless potential that lies within each of them. These activities not only enriched their lives but also fostered a sense of community and belonging. The Valsella Foundation provided us with comprehensive training and support, ensuring that we were well-equipped to meet the needs of the children. The guidance from experienced staff members was invaluable, and I always felt confident in my ability to contribute meaningfully. The collaborative spirit among volunteers created a supportive environment where we could share ideas and learn from each other. Witnessing the positive changes in the children’s lives has been incredibly rewarding. Many of them have made significant progress in their studies, developed new skills, and gained a stronger sense of self-worth. Knowing that I played a part in their journey towards a brighter future is an indescribable feeling. Volunteering in Cambodia has also deepened my understanding of global issues and the importance of community involvement. It has taught me the value of empathy, patience, and perseverance. The bonds formed with the children and fellow volunteers will always hold a special place in my heart. I wholeheartedly recommend Valsella Foundation’s program to anyone looking to make a tangible difference. The experience is challenging yet immensely fulfilling, and the impact you can have on these children’s lives is truly profound. Volunteering in these orphanages has been a journey of growth, compassion, and unwavering hope, and it is an experience I will cherish forever."
    },
    {
        id: "bt575ej5ktqo4e8",
        title: "Helping in Homeless shelters",
        where: "Every Province in Cambodia and Phnom Penh",
        info: "There are around 3000 homeless people in Cambodia right now. These 3000 people can be rehabilitated to be able to be functioning members of society. That's why we are building homeless shelters around Cambodia so that we can provide them with food, water, clothes, and shelter.",
        video: "https://www.youtube.com/embed/5EN3_7Nl0Qk?si=Fk2ZNUMg2zyHMAEb",
        username: "Steven Wolfe",
        image: "./images/1663090168915.jpg",
        testimony: "Volunteering with the Valsella Foundation in homeless shelters across Cambodia has been an eye-opening and deeply rewarding journey. When I first joined the program, I was eager to make a difference, but I never anticipated just how much this experience would transform my own perspective on life. From the very beginning, I was struck by the resilience and strength of the individuals I met. Despite facing immense hardships, many of the shelter residents exhibited incredible courage and hope. My role as a volunteer was to provide support, lend a listening ear, and help create a more stable and nurturing environment for those in need. Whether it was assisting with daily operations, organizing activities, or simply offering companionship, every task carried a profound sense of purpose. One of the most impactful moments for me was working with a young man named Sokha. He had been living on the streets for years, struggling to find a foothold in life. Through the Valsella Foundation’s program, we were able to provide him with not only a safe place to stay but also access to vocational training and job placement assistance. Witnessing Sokha’s transformation from a state of despair to finding employment and regaining his confidence was incredibly moving. His story is just one of many that highlights the vital role these shelters play in rebuilding lives. The training and support provided by Valsella Foundation were exceptional. We were equipped with the skills and knowledge needed to address various challenges and make a meaningful impact. The camaraderie among the volunteers was also a significant source of strength and motivation. We supported each other, shared our experiences, and worked together towards common goals. What stood out to me the most was the sense of community that developed within the shelters. People from different walks of life came together, forming bonds and supporting one another in ways that went beyond mere survival. It was a powerful reminder that everyone deserves dignity, respect, and the opportunity to build a better future. Volunteering in Cambodia has deepened my understanding of the complexities of homelessness and the importance of holistic support systems. It has taught me the value of empathy, patience, and the power of human connection. The experiences and friendships I gained during this program have left an indelible mark on my heart. I highly recommend Valsella Foundation’s volunteer program to anyone looking to make a tangible difference. It’s challenging but profoundly fulfilling work that changes lives, including your own. Volunteering in these shelters has been a journey of growth, compassion, and hope, and it is an experience I will carry with me forever."
    },
]
export default PROGRAMS